# Workflow Name
name: Create Dev Release on Push

# Workflow Trigger: Triggers when pushing to the main branch
on:
  push:
    branches:
      - main  # Branch for development builds

# Define a job named 'build-and-release'
jobs:
  build-and-release:
    # Specify the runner for this job. Ensure the tag here matches the tag used when registering the runner
    runs-on: linux-amd64 # Runner Tag
    steps:
      # ----------------------------------------------------------------------
      # Step 1: Debug - Print key Gitea variables (Optional, but recommended to keep)
      # ----------------------------------------------------------------------
      - name: Debug Gitea Context Variables
        run: |
          echo "Gitea Repository: ${{ gitea.repository }}"
          echo "Gitea SHA: ${{ gitea.sha }}"

      # ----------------------------------------------------------------------
      # Step 2: Configure Git Authentication
      # ----------------------------------------------------------------------
      - name: Configure Git for checkout
        run: |
          GITEA_SERVER_URL="${{ gitea.server_url }}"
          AUTH_HEADER="Authorization: basic $(echo -n "gitea-actions:${{ secrets.GITEA_TOKEN }}" | base64)"
          git config --global "http.${GITEA_SERVER_URL}.extraheader" "${AUTH_HEADER}"
          git config --global --add safe.directory "${{ gitea.workspace }}"
      
      # ----------------------------------------------------------------------
      # Step 3: Checkout Code
      # ----------------------------------------------------------------------
      - name: Checkout repository
        run: |
          git clone --depth 1 --branch ${{ gitea.ref_name }} "${{ gitea.server_url }}/${{ gitea.repository }}.git" .

      # ----------------------------------------------------------------------
      # Step 4: Clean up authentication information (This is a good security practice)
      # ----------------------------------------------------------------------
      - name: Clean up Git credentials
        if: always()
        run: |
          git config --global --unset-all "http.${{ gitea.server_url }}.extraheader"

      # ----------------------------------------------------------------------
      # Step 5: Set up Node.js Environment
      # ----------------------------------------------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # ----------------------------------------------------------------------
      # Step 6: Install Dependencies and Build the Project
      # ----------------------------------------------------------------------
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      # ----------------------------------------------------------------------
      # Step 7: Prepare Release Information and Artifacts
      # ----------------------------------------------------------------------
      - name: Prepare release assets
        id: prepare_assets
        run: |
          SHORT_SHA=$(echo "${{ gitea.sha }}" | cut -c1-8)
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITEA_ENV
          (cd dist && zip -r "../liveplayer.zip" .)

      # ----------------------------------------------------------------------
      # New Step 8: Analyze Commit Message to Determine Release Type
      # 1. Check if the commit message matches the version number format (e.g., 1.2.3, 4.5.6-rc.1, 7.8.9-SNAPSHOT)
      #    Regular expression matches X.Y.Z or X.Y.Z-suffix format
      # 2. If it is a version number, set IS_VERSION_COMMIT=true and the release details
      # 3. If not, set IS_VERSION_COMMIT=false to trigger the subsequent development build process
      # ----------------------------------------------------------------------
      - name: Analyze Commit Message for Versioning
        id: commit_analyzer
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%s "${{ gitea.sha }}")
          if [[ "$COMMIT_MSG" =~ ^([0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.-]+)?)$ ]]; then
            VERSION_TAG="${BASH_REMATCH[1]}"
            echo "Commit message is a version: ${VERSION_TAG}"
            echo "IS_VERSION_COMMIT=true" >> $GITEA_ENV
            echo "TAG_NAME=${VERSION_TAG}" >> $GITEA_ENV
            
            if [[ "$VERSION_TAG" == *-rc* ]]; then
              echo "Release type: Release Candidate"
              echo "RELEASE_NAME=Release Candidate ${VERSION_TAG}" >> $GITEA_ENV
              echo "PRERELEASE=true" >> $GITEA_ENV
            elif [[ "$VERSION_TAG" == *-* ]]; then
              echo "Release type: Snapshot"
              echo "RELEASE_NAME=Snapshot ${VERSION_TAG}" >> $GITEA_ENV
              echo "PRERELEASE=true" >> $GITEA_ENV
            else
              echo "Release type: Full Release"
              echo "RELEASE_NAME=Release ${VERSION_TAG}" >> $GITEA_ENV
              echo "PRERELEASE=false" >> $GITEA_ENV
            fi
          else
            echo "Commit message :$COMMIT_MSG: is not a version. Proceeding with dev build."
            echo "IS_VERSION_COMMIT=false" >> $GITEA_ENV
          fi

      # ------------------------------------------------------------------
      # Step 9A: If it's a version number commit, create a Full, RC, or Snapshot Release
      # This step only runs when env.IS_VERSION_COMMIT == 'true'
      # ------------------------------------------------------------------
      - name: Create Versioned Release (if applicable)
        id: create_versioned_release
        if: env.IS_VERSION_COMMIT == 'true'
        run: |
          COMMIT_MSG_FROM_GIT=$(git log -1 --pretty=%B "${{ gitea.sha }}")
          BODY_TEXT=$(printf "Release for version **%s**.\n\nCommit details:\n> %s" "${{ env.TAG_NAME }}" "${COMMIT_MSG_FROM_GIT}")

          JSON_BODY=$(jq -n \
            --arg tag "${{ env.TAG_NAME }}" \
            --arg name "${{ env.RELEASE_NAME }}" \
            --arg body "${BODY_TEXT}" \
            --argjson prerelease ${{ env.PRERELEASE }} \
            '{
              "tag_name": $tag,
              "name": $name,
              "body": $body,
              "prerelease": $prerelease
            }'
          )

          echo "Generated JSON Body for Versioned Release:"
          echo "${JSON_BODY}"

          curl -sL \
            -X POST \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.RELEASE_PAT }}" \
            -d "${JSON_BODY}" \
            -o response.json \
            "${{ gitea.server_url }}/api/v1/repos/${{ gitea.repository }}/releases"

          UPLOAD_URL=$(jq -r .upload_url response.json)
          echo "UPLOAD_URL=${UPLOAD_URL}" >> $GITEA_ENV

      # ------------------------------------------------------------------
      # Step 9B: If it's not a version number commit, create a Dev Release (retains original behavior)
      # This step only runs when env.IS_VERSION_COMMIT == 'false'
      # ------------------------------------------------------------------
      - name: Create Dev Release (if not a version commit)
        id: create_dev_release # Changed ID to avoid conflict
        if: env.IS_VERSION_COMMIT == 'false'
        run: |
          COMMIT_MSG_FROM_GIT=$(git log -1 --pretty=%B "${{ gitea.sha }}")
          BODY_TEXT=$(printf "Automated development build from commit %s:\n\n> %s" "${{ env.SHORT_SHA }}" "${COMMIT_MSG_FROM_GIT}")

          JSON_BODY=$(jq -n \
            --arg sha ${{ env.SHORT_SHA }} \
            --arg body "${BODY_TEXT}" \
            '{
              "tag_name": ("git-" + $sha),
              "name": ("Dev Build git-" + $sha),
              "body": $body,
              "prerelease": true
            }'
          )

          echo "Generated JSON Body for Dev Release:"
          echo "${JSON_BODY}"

          curl -sL \
            -X POST \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.RELEASE_PAT }}" \
            -d "${JSON_BODY}" \
            -o response.json \
            "${{ gitea.server_url }}/api/v1/repos/${{ gitea.repository }}/releases"

          UPLOAD_URL=$(jq -r .upload_url response.json)
          echo "UPLOAD_URL=${UPLOAD_URL}" >> $GITEA_ENV

      # ------------------------------------------------------------------
      # Step 10: Upload attachments to the created Release
      # 1. Dynamically get the UPLOAD_URL generated in Step 9A or 9B
      # 2. Upload all artifacts
      # ------------------------------------------------------------------
      - name: Upload Release Assets via API
        run: |
          UPLOAD_URL="${{ env.UPLOAD_URL }}"
          
          if [ -z "$UPLOAD_URL" ] || [ "$UPLOAD_URL" == "null" ]; then
            echo "::error::Failed to get upload URL from a previous step."
            exit 1
          fi

          curl -sL \
            -X POST \
            -H "Content-Type: application/zip" \
            -H "Authorization: token ${{ secrets.RELEASE_PAT }}" \
            --data-binary "@liveplayer.zip" \
            "${UPLOAD_URL}?name=liveplayer.zip" > /dev/null

          for file in dist/*; do
            if [ -f "$file" ]; then
              FILENAME=$(basename "$file")
              echo "Uploading ${FILENAME}..."
              curl -sL \
                -X POST \
                -H "Content-Type: $(file -b --mime-type "$file")" \
                -H "Authorization: token ${{ secrets.RELEASE_PAT }}" \
                --data-binary "@$file" \
                "${UPLOAD_URL}?name=${FILENAME}" > /dev/null
            fi
          done